### ISSUE TITLE
How to compile Chiaki on Linux (Ubuntu & Debian) 

### ISSUE THREAD

**Issue by zicos77** [thestr4ng3r/chiaki#191]
## Chiaki link Source : 
https://github.com/thestr4ng3r/chiaki

## linux commands :
```
apt-get update -y

apt-get install git cmake python3-pip qt5-default qtmultimedia5-dev python3-pyqt5.qtopengl python-pyqt5.qtsvg libqt5svg5-dev pyqt5-dev python-pyqt5.qtsvg ffmpeg x264 libavcodec-dev libopus-dev openssl protobuf-compiler libssl-dev libsdl2-dev -y

pip3 uninstall protobuf -y
pip3 uninstall google -y
pip3 install google
pip3 install protobuf

mkdir /Chiaki 
cd /Chiaki

git clone https://github.com/thestr4ng3r/chiaki.git
cd chiaki

git submodule update --init

mkdir build && cd build

cmake ../ -DCMAKE_INSTALL_PREFIX=/Chiaki/Chiaki_Bin
make
make install
cd /Chiaki/Chiaki_Bin
```
## Credit :
thestr4ng3r (Florian Märkl)

**Comment by scaryrawr** [comment]
You also need to install `libqt5multimedia5-plugins` (not required for building), but otherwise there will be no runtime audio, `QAudioDeviceInfo::defaultOutputDevice()`, will return empty audio device that doesn't support any formats.

**Comment by DanielCMiranda** [comment]
Hi! I'm trying to compile on Ubuntu 18.04 but I'm having some issues. Do anyone know what the problem could be? In theory, I installed all the specified dependencies and also some other I thought could solve the issues, but with no success.

error: use of enum ‘AVHWDeviceType’ without previous declaration
error: ‘AV_HWDEVICE_TYPE_NONE’ was not declared in this scope
error: ‘AVCodecHWConfig’ does not name a type; did you mean ‘AVCodecContext’?
(more errors omitted)...

**Comment by BDeveau** [comment]
I'm having the same issue has Daniel. videodecoder.cpp is failing during make, this is the first error listed.

**Comment by independentcod** [comment]
https://github.com/independentcod/Chiaki-AutoCompile

**Comment by bradleybowman** [comment]
@independentcod 

I tried your script and it ultimately worked great, thank you.  

I will note that it failed the first time because on my install of Ubuntu 20.04 I didn't have the `protobuf-compiler` package installed.  Your script doesn't appear to install that one; if anybody else has that issue the error message generated is `Could not find protoc` which is pretty straightforward, but yknow.
